export const SET_USER_DATA = 'SET_USER_DATA';

export const SET_USERS_LIST = 'SET_USERS_LIST';

export const ADD_NEW_USER = 'ADD_NEW_USER';
export const REMOVE_USER = 'REMOVE_USER';

export const SELECT_DIALOG = 'SELECT_DIALOG';
export const CLEAN_UP_DIALOG = 'CLEAN_UP_DIALOG';

export const UPDATE_MESSAGES_LIST = 'UPDATE_MESSAGES_LIST';
